### ISSUE TITLE
Add rolled initiative to the Foundry initiative tracker.

### ISSUE THREAD

**Issue by c1t4rd** [OctarineSourcerer/cyberpunk2020#131]
I know it says that it sadly doesn't add initiative into the Foundry tracker, but i wonder if it's even possible to do that.

**Comment by OctarineSourcerer** [comment]
Hi @c1t4rd! I had some time today, figured I'd look at this, and... it seems to actually work, possibly due to forever ago when I made iniative be able to use Combat Sense in `system.json`. Pleasant surprises!

Do you know where it says it doesn't add iniative into the Foundry tracker? If it works for you, I might be able to change that.

(You might see an error pop up in the console when creating encounters: `cannot read properties of undefined (reading 'combatantId')`. This is apparently a vanilla Foundry thing, and relatively harmless, see https://github.com/foundryvtt/foundryvtt/issues/9718)

**Comment by c1t4rd** [comment]
When I press on the Initiative button in the character sheet, here's what it says:

![image](https://github.com/OctarineSourcerer/cyberpunk2020/assets/94686479/9c251ae6-e595-4a86-a080-58110a73618e)

![image](https://github.com/OctarineSourcerer/cyberpunk2020/assets/94686479/966da4b3-3aa4-45a3-a514-4996fda6db62)

**Comment by OctarineSourcerer** [comment]
Ah, sorry, I thought I'd responded here a while back. It turns out that adding via the token - right click the token, click sword-and-shield - added to the initiative just fine, from which you could roll initiative.

The button on the sheet... did not do that. The API for rolling on the combat encounter seems a little gnarly, or at least not documented as well as I'd like, but that should work as of commit 4c028f4a3408699245709cdbe132f71393a5e668. Let me know if something goes wrong; I very much wish past me had set up a test harness for the project.
