### ISSUE TITLE
[Bug Report] When copying characters, skill isn't copied.

### ISSUE THREAD

**Issue by Paulkwk** [OctarineSourcerer/cyberpunk2020#141]
When using the duplicate function to duplicate characters(I use it mostly for creating similar npcs), skill numbers isn't been copied.

**Comment by OctarineSourcerer** [comment]
This should be fixed now. It's basically to do with the fact that you can just have custom skills in Cyberpunk2020, which FoundryVTT would be none too happy about; so, Actors in CP2020 have their skills as items. If I were to go back and redesign, it's possible I'd have the vanilla skills baked-into the actors, and items for extra skills, but then there'd be two ways of dealing with the same thing and... TL;DR no free-lunch solution to custom skills, though I may test alternatives some time.

Because Actors had their skills as items, on creation they go and fetch their default skills from a compendium. However, in the case of duplicating (which you found, thank you), they _already_ have skills, and thus should not overwrite those. That check is now made.

This isn't pushed to an official version yet, but if you pull from main it oughta work.
