### ISSUE TITLE
Skills are broken in 3.10

### ISSUE THREAD

**Issue by BrianC1970** [OctarineSourcerer/cyberpunk2020#147]
![image](https://github.com/OctarineSourcerer/cyberpunk2020/assets/173972097/cc029cb3-f3c1-4fc4-a65c-9ed528435deb)
 So the attribute that is assigned to the skill disapears after you try and edit it. This make the skills broken and not useable. can this be fixed as the game really is unplayable.

BrianC 
Discord ID: brianc1970

**Comment by BrianC1970** [comment]
Just, rolled back to 3.9 and skills work fine.

**Comment by OctarineSourcerer** [comment]
This should be fixed in 3.11. Sorry for the issue! In short, I'd started using Foundry's less-deprecated methods of fetching system template data if people were on v12 or above (so I could let people still use older versions of Foundry if they needed to).
Unfortunately, it turns out that ended up returning full objects describing the shape of stats, instead of just their names, hence the breakage. This should now be fixed, though you may have to manually reset stats that have broken.
