### ISSUE TITLE
Add new GEAR.Class Vehicles

### ISSUE THREAD

**Issue by drowzero0** [OctarineSourcerer/cyberpunk2020#49]
It would be nice if there was an Itemclass for Vehicles.
It should contain a bigger Frame for Pictures to upload more detailed Stuff.
Following stats should be included as in the picture:
+ Detailtab for descriptions
![image](https://user-images.githubusercontent.com/62395017/114747509-34485700-9d51-11eb-8a85-5c2fc3cb3698.png)

**Comment by OctarineSourcerer** [comment]
This should be in develop now if you want to try it :) I know it doesn't have a bigger picture, buuuut if you look in the settings there should look cool!

![image](https://user-images.githubusercontent.com/6842867/117335701-55edb780-ae93-11eb-9636-12899df4e32f.png)


At the moment, maneuverability is just cosmetic, and fuel will always show gallons and miles per gallon, though that's likely to change at some point. I do plan to have a control roll as well, but I want to have a more unified system of providing modifiers under the hood. The one for ranged attack rolls works well, but it's... well, it's implemented specifically for that, and I need to make it more generic.

Sorry for the hiatus! Game jam happened, and a lot of evenings have been busy since. Enjoy!

**Comment by drowzero0** [comment]
thanks this looks great in your preview.
i will test that out tomorrow, since i currently have trouble reaching my foundryserver.
when i got this fixed, i will let you know if there are still some kinds of trouble.

thanks a lot so far =)

**Comment by OctarineSourcerer** [comment]
No worries. Best of luck with fixing the server stuff!

**Comment by drowzero0** [comment]
got my server back running yesterday and tested the car sheet bevor your release.
i really like this sheet. helps to put in some vehicles with their stats =)
only thing i am wondering about.
yours shows some bars which i can not find.

![image](https://user-images.githubusercontent.com/62395017/117536523-b5ff6d80-affb-11eb-8411-5d70735a2104.png)
