### ISSUE TITLE
Allow for adding new skills/editing names

### ISSUE THREAD

**Issue by OctarineSourcerer** [OctarineSourcerer/cyberpunk2020#54]
This isn't a huge priority with how many skills cyberpunk has, but is particularly needed for Expert and Know Language, where you can add subskills.

One way of doing this would be to make skills items. This gets a little gnarly though, as each skill having a whole sheet feels WEIRD - the skills section is kind of already a sheet for it, but the biggest argument against it is that I'd likely have to hook into entity creation just to make sure that all actors have the starting stats instead of template managing that.

**Comment by drowzero0** [comment]
in my case i would love to have that, since nearly every player of my table has some unique skills like "CombatDrinking" or
"Ninjutsu"  and so on.
at the moment those players are having a notice in the "Life" tab about those.
creation of whole sheets for every skill would be too much of a pain as you said.
but creating a sheet with a referenced stat below  extra tabs like "Basic skills and Extra Skills" and creating those skills as extra item could be an option.

**Comment by OctarineSourcerer** [comment]
This got released a couple days ago and is released, closing now :)
