### ISSUE TITLE
Humanity cost rolls aren't working

### ISSUE THREAD

**Issue by TheWing** [OctarineSourcerer/cyberpunk2020#89]
Right off the bat this might be due to me running foundry 0.8.8 instead of what's supported so far.

When setting up cyberware, the humanity cost roll button seems to not do anything, and it seems to be grayed out even if the required roll needs dice (not sure if that matters at all)

Not really a huge issue as these rolls are pretty simple to do by hand, but I imagine the roll button would also set the humanity loss value accordingly.

Modules I have that might cause something:
Actually Private Rolls, Better Roll Tables, Roll From Compendium
(I do have more modules but I can't imagine how they'd impact how rolls behave)

**Comment by OctarineSourcerer** [comment]
Nah, we support Foundry 0.8.x, you're all good there :)

You're correct on it not working - that should be fixed in commit cb29c3d, will be in whenever the next release hits. It does now indeed set the humanity loss value accordingly.

Cheers for the report! (and for the module list - though it didn't end up relevant here, I appreciate it still)
